$(document).ready(function() {
    $("#one").click(function(){
        $("#two").fadeIn();
    });
    $("#two").click(function(){
        $("#three").fadeIn();
    });
    $("#three").click(function(){
        $("#four").fadeIn();
    });
    $("#four").click(function(){
        $("#five").fadeIn();
    });
    $("#five").click(function(){
        $("#six").fadeIn();
    });
    $("#six").click(function(){
        $("#seven").fadeIn();
    });
    $("#seven").click(function(){
        $("#eight").fadeIn();
    });
    $("#eight").click(function(){
        $("#nine").fadeIn();
    });
    $("#nine").click(function(){
        $("#ten").fadeIn();
    });
});