$(document).ready(function() {
    $("#one").mouseenter(function(){
        $("#two").fadeIn();
    });
    $("#two").mouseenter(function(){
        $("#three").fadeIn();
    });
    $("#three").mouseenter(function(){
        $("#four").fadeIn();
    });
    $("#four").mouseenter(function(){
        $("#five").fadeIn();
    });
    $("#five").mouseenter(function(){
        $("#six").fadeIn();
    });
    $("#six").mouseenter(function(){
        $("#seven").fadeIn();
    });
    $("#seven").mouseenter(function(){
        $("#eight").fadeIn();
    });
    $("#eight").mouseenter(function(){
        $("#nine").fadeIn();
    });
    $("#nine").mouseenter(function(){
        $("#ten").fadeIn();
    });
    $("#ten").mouseenter(function(){
        $("#eleven").fadeIn();
    });
    $("#eleven").mouseenter(function(){
        $("#twelve").fadeIn();
    });
    $("#twelve").mouseenter(function(){
        $("#thirteen").fadeIn();
    });
    $("#thirteen").mouseenter(function(){
        $("#fourteen").fadeIn();
    });
    $("#fourteen").mouseenter(function(){
        $("#fifteen").fadeIn();
    });
    $("#fifteen").mouseenter(function(){
        $("#sixteen").fadeIn();
    });
    $("#sixteen").mouseenter(function(){
        $("#seventeen").fadeIn();
    });
    $("#seventeen").mouseenter(function(){
        $("#eighteen").fadeIn();
    });
    $("#eighteen").mouseenter(function(){
        $("#nineteen").fadeIn();
    });
    $("#nineteen").mouseenter(function(){
        $("#twenty").fadeIn();
    });
    $("#twenty").mouseenter(function(){
        $("#twentyone").fadeIn();
    });
    $("#twentyone").mouseenter(function(){
        $("#twentytwo").fadeIn();
    });
    $("#twentytwo").mouseenter(function(){
        $("#twentythree").fadeIn();
    });
    $("#twentythree").mouseenter(function(){
        $("#twentyfour").fadeIn();
    });
    $("#twentyfour").mouseenter(function(){
        $("#twentyfive").fadeIn();
    });
    $("#twentyfive").mouseenter(function(){
        $("#twentysix").fadeIn();
    });
    $("#twentysix").mouseenter(function(){
        $("#twentyseven").fadeIn();
    });
    $("#twentyseven").mouseenter(function(){
        $("#twentyeight").fadeIn();
    });
});