$(document).ready(function() {
    $("#one").click(function(){
        $("#two").fadeIn();
    });
    $("#two").click(function(){
        $("#three").fadeIn();
    });
    $("#three").click(function(){
        $("#four").fadeIn();
    });
    $("#four").click(function(){
        $("#five").fadeIn();
    });
    $("#five").click(function(){
        $("#six").fadeIn();
    });
    $("#six").click(function(){
        $("#seven").fadeIn();
    });
    $("#seven").click(function(){
        $("#eight").fadeIn();
    });
    $("#eight").click(function(){
        $("#nine").fadeIn();
    });
    $("#nine").click(function(){
        $("#ten").fadeIn();
    });
    $("#ten").click(function(){
        $("#eleven").fadeIn();
    });
    $("#eleven").click(function(){
        $("#twelve").fadeIn();
    });
    $("#twelve").click(function(){
        $("#thirteen").fadeIn();
    });
    $("#thirteen").click(function(){
        $("#fourteen").fadeIn();
    });
    $("#fourteen").click(function(){
        $("#fifteen").fadeIn();
    });
    $("#fifteen").click(function(){
        $("#sixteen").fadeIn();
    });
    $("#sixteen").click(function(){
        $("#seventeen").fadeIn();
    });
    $("#seventeen").click(function(){
        $("#eighteen").fadeIn();
    });
    $("#eighteen").click(function(){
        $("#nineteen").fadeIn();
    });
    $("#nineteen").click(function(){
        $("#twenty").fadeIn();
    });
    $("#twenty").click(function(){
        $("#twentyone").fadeIn();
    });
    $("#twentyone").click(function(){
        $("#twentytwo").fadeIn();
    });
    $("#twentytwo").click(function(){
        $("#twentythree").fadeIn();
    });
    $("#twentythree").click(function(){
        $("#twentyfour").fadeIn();
    });
    $("#twentyfour").click(function(){
        $("#twentyfive").fadeIn();
    });
    $("#twentyfive").click(function(){
        $("#twentysix").fadeIn();
    });
    $("#twentysix").click(function(){
        $("#twentyseven").fadeIn();
    });
});